import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderHome from "@/components/ui/header-home";
import { Theme } from "@radix-ui/themes";
import Navbar from "@/components/ui/navbar";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BetterCare",
  description: "Generated by BetterCare",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {

  return (
    <html lang="en">
      <body className={`${inter.className} overflow-auto`}>
        <Providers>
          <Theme>
            <HeaderHome />
            {children}
            <Navbar />
          </Theme>
        </Providers>
      </body>
    </html>
  );
}
